kind: Service
apiVersion: v1
metadata:
  name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-service
  namespace: default
spec:
  selector:
    app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${CICD_GIT_REPO_NAME}
  namespace: default
  labels:
    app: ${CICD_GIT_REPO_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
  namespace: default
  labels:
    app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
  template:
    metadata:
      labels:
        app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
    spec:
      imagePullSecrets:
      - name: registry-edugem
      volumes:
      - name: ${CICD_GIT_REPO_NAME}-ps
        persistentVolumeClaim:
          claimName: ${CICD_GIT_REPO_NAME}
      containers:
      - name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
        image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: ${CICD_GIT_REPO_NAME}-ps
          mountPath: /archivos
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
  namespace: default
spec:
  rules:
  - host: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}.edu-edomex.gob.mx
    http:
      paths:
      - backend:
          serviceName: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-service
          servicePort: 8080
